backend:
    needs: []
    image: python:latest
    tags:
        - docker

    before_script:
        - python -V
        - pip install poetry
        - cd backend
        - poetry install

    script:
        - poetry run black . --check
        - poetry run isort . --check-only
        - poetry run mypy
        - poetry run pytest
        - poetry run coverage run -m pytest
        - poetry run coverage report --skip-empty

frontend:
    needs: []
    image: node:latest
    tags:
        - docker

    cache:
        key: npm
        paths:
            - frontend/.npm/

    before_script:
        - node --version
        - npm --version
        - cd frontend
        - npm ci --cache .npm --prefer-offline

    script:
        - npm run format\:check
        - npm run lint
        - npx quasar build
