backend:
    needs: []
    image: python:latest
    tags:
        - docker

    before_script:
        - python -V
        - pip install poetry
        - cd backend
        - poetry install

    script:
        - poetry run black . --check
        - poetry run isort . --check-only
        - poetry run mypy
        - poetry run pytest

frontend:
    needs: []
    image: node:latest
    tags:
        - docker

    before_script:
        - node --version
        - npm --version
        - cd frontend
        - npm ci

    script:
        - npm run format\:check
        - npm run lint
        - npx quasar build
