from typing import List

class CryptContext:
    def __init__(self, schemes: List[str], deprecated: str): ...
    def hash(self, password: str) -> str: ...
    def verify(self, password: str, hash: str) -> bool: ...
